### ISSUE TITLE
Plugin Does Not Seem to Work in Foreman 1.7+

### ISSUE THREAD

**Issue by jstuart** [domcleal/foreman_param_lookup#2]
Using both Foreman 1.7(.5) and Foreman 1.8(.2) the param_lookup endpoint does not return any information about classes that are not attached to a given host.

For example, given a host foo.local, which includes modules named bar and baz, but does not include another configured module named qux, the following output is expected:
```
$ curl http://foreman/param_lookup?host=foo.local&class=qux
--- 
  qux:
    param1: value
    param2: "another value"
```

In 1.7+, the following output is actually returned:
```
$ curl http://foreman/param_lookup?host=foo.local&class=qux
--- 
  bar:
  baz:
```

Looking up included classes works as expected:
```
$ curl http://foreman/param_lookup?host=foo.local&class=bar
--- 
  bar:
    param1: value
    param2: "another value"
  baz:
```

And:
```
$ curl http://foreman/param_lookup?host=foo.local&class=baz
--- 
  bar:
  baz:
    param1: value
    param2: "another value"
```

This seems to be fairly easy to reproduce.  I am happy to help troubleshoot in any way I can.

**Comment by losnir** [comment]
+1

It's a shame, since this bug makes the plugin useless (Foreman already sends Smart Class Parameters to nodes with directly attaches classes).

**Comment by losnir** [comment]
Hey @jstuart & @domcleal,

I just created a PR with a fix for this issue.
Will appreciate your feedback.

\- Nir
